# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
name: Trailer

on:
  workflow_dispatch:
    inputs:
      pr_commits:
        required: true
      pr_head_repo:
        required: true
      pr_head_ref:
        required: true
      trailer:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TRAILER_BOT_TOKEN }}
          repository: ${{ inputs.pr_head_repo }}
          ref: ${{ inputs.pr_head_ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Amend all pull request commits with the new trailer
        run: |
          set -xe
          # configure git identity to the most recent committer
          GIT_COMMITTER_NAME=$(git log -1 --pretty=%cN)
          GIT_COMMITTER_EMAIL=$(git log -1 --pretty=%cE)
          git config set user.name "$GIT_COMMITTER_NAME"
          git config set user.email "$GIT_COMMITTER_EMAIL"
          export GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
          # add commit-msg hook to remove duplicate trailers and ensure correct ordering
          rm -f .git/hooks/commit-msg
          ln -s ../../devtools/commit-msg .git/hooks/commit-msg
          # rewrite all commit messages, appending the trailer
          GIT_TRAILER_DEBUG=1 git rebase 'HEAD~${{ inputs.pr_commits }}' \
            --exec 'git commit -C HEAD --no-edit --amend --trailer="${{ inputs.trailer }}"'
          git push --force origin "${{ inputs.pr_head_ref }}"
