# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
name: Comment

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  actions: write

jobs:
  posted:
    if: ${{ github.event.issue.pull_request && (contains(github.event.comment.body, 'Acked-by:') || contains(github.event.comment.body, 'Tested-by:')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Resolve trailer data
        uses: actions/github-script@v7
        with:
          script: |
            const regexp = /(acked|tested)-by:\s+(\w[^<]+\w)\s+<?([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})>?/i;
            const match = context.payload.comment.body.match(regexp);
            if (!match) {
              return;
            }
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'add-trailer.yml',
              ref: 'main',
              inputs: {
                pr_number: pr.number,
                pr_commits: pr.commits,
                pr_head_repo: pr.head.repo.full_name,
                pr_head_ref: pr.head.ref,
                trailer: `${match[1]}-by: ${match[2]} <${match[3]}>`,
              }
            });
