# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
name: Review

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Resolve reviewer name and email
        id: trailer
        uses: actions/github-script@v7
        with:
          script: |
            const user = await github.rest.users.getByUsername({username: context.actor});
            if (user.name == null) {
              core.setFailed(`user @${context.actor} does not expose their real name`);
              process.exit(1);
            }
            if (user.email == null) {
              await exec.exec('sh', ['-c', `git log --pretty=%aE --author="${user.name}" | head -n1`], {
                failOnStdErr: true,
                listeners: {
                  stdline: (data) => {
                    user.email = data.toString();
                  },
                },
              });
              if (user.email == null) {
                core.setFailed(`user @${context.actor} does not expose their email and is unknown from git history`);
                process.exit(1);
              }
            }
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'add-trailer.yml',
              ref: 'main',
              inputs: {
                pr_number: github.event.pull_request.number,
                pr_commits: github.event.pull_request.commits,
                pr_head_repo: github.event.pull_request.head.repo.full_name,
                pr_head_ref: github.event.pull_request.head.ref,
                trailer: `Reviewed-by: ${user.name} <${user.email}>`,
              }
            });
